// GET
export const GET_REPOSITORIES_FULFILLED = "GET_REPOSITORIES_FULFILLED";
export const GET_REPOSITORIES_PENDING = "GET_REPOSITORIES_PENDING";
export const GET_REPOSITORIES_REJECTED = "GET_REPOSITORIES_REJECTED";
